// Sync the plugin's vendored price table from the pi-ai provider data bundled
// with DSH (`@earendil-works/pi-ai/dist/providers/data/*.json`).
//
// Why vendor instead of importing pi-ai at runtime: a browser/out-of-tree
// plugin cannot resolve `@earendil-works/pi-ai` (it lives nested inside the
// DSH install), and the client half runs in the browser where it cannot load
// Node packages at all. Vendoring the *data* (the authoritative per-model cost
// table) keeps the plugin self-contained while still tracking the exact prices
// DSH's own billing uses.
//
// Re-run whenever DSH upgrades pi-ai:
//   node scripts/sync-prices.mjs [path-to-pi-ai-dist/providers/data]
//
// Output: lib/prices.generated.js (ESM), two maps:
//   PRICES_BY_PROVIDER[provider]["<model>"] = { input, output, cacheRead, cacheWrite }
//   PRICES_BY_MODEL["<model>"]            = { input, output, cacheRead, cacheWrite }
// `PRICES_BY_MODEL` resolves the model id against the first-party vendor
// (deepseek/anthropic/openai/…) so a reseller/gateway listing for the same id
// never shadows the vendor's official list price.

import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");

// First-party vendor files first (highest priority for the model-id fallback).
// Resellers / gateways / token-plans follow; any id they repeat is ignored.
const VENDOR_FIRST = [
  "deepseek.json",
  "anthropic.json",
  "openai.json",
  "openai-codex.json",
  "google.json",
  "xai.json",
  "mistral.json",
  "groq.json",
  "cerebras.json",
  "nvidia.json",
  "zai.json",
  "moonshotai.json",
  "minimax.json",
  "kimi-coding.json",
  "ant-ling.json",
  "xiaomi.json",
  "amazon-bedrock.json",
  "azure-openai-responses.json",
  "github-copilot.json",
  "google-vertex.json",
];

const DEFAULT_DATA_DIR =
  "/opt/homebrew/lib/node_modules/@deepseek-ai/dsh/node_modules/@earendil-works/pi-ai/dist/providers/data";

const dataDir = resolve(process.argv[2] ?? DEFAULT_DATA_DIR);
if (!existsSync(dataDir)) {
  console.error(`price data dir not found: ${dataDir}`);
  process.exit(1);
}

const files = readdirSync(dataDir).filter((f) => f.endsWith(".json"));
const ordered = [
  ...VENDOR_FIRST.filter((f) => files.includes(f)),
  ...files.filter((f) => !VENDOR_FIRST.includes(f)).sort(),
];

const byProvider = {};
const byModel = {};

function normalizeCost(cost) {
  // Base cost buckets; tiers are deliberately flattened (per-request volume
  // tiers cannot be reproduced from the harness's persisted usage buckets).
  const n = (v) => (typeof v === "number" && Number.isFinite(v) ? v : 0);
  return {
    input: n(cost?.input),
    output: n(cost?.output),
    cacheRead: n(cost?.cacheRead),
    cacheWrite: n(cost?.cacheWrite),
  };
}

let modelCount = 0;
for (const file of ordered) {
  let data;
  try {
    data = JSON.parse(readFileSync(join(dataDir, file), "utf8"));
  } catch (e) {
    console.error(`skip ${file}: ${e.message}`);
    continue;
  }
  for (const models of Object.values(data)) {
    if (!models || typeof models !== "object") continue;
    for (const [modelId, entry] of Object.entries(models)) {
      if (!entry || typeof entry !== "object") continue;
      const provider = typeof entry.provider === "string" ? entry.provider : file.replace(/\.json$/, "");
      const cost = normalizeCost(entry.cost);
      (byProvider[provider] ??= {})[modelId] = cost;
      if (!(modelId in byModel)) {
        byModel[modelId] = cost;
        modelCount++;
      }
    }
  }
}

const header =
  "// Generated by scripts/sync-prices.mjs — do not edit.\n" +
  "// Source: @earendil-works/pi-ai dist/providers/data/*.json (USD per 1M tokens).\n" +
  `// Models (model-id fallback): ${modelCount}.\n`;

const body =
  `export const PRICES_BY_PROVIDER = ${JSON.stringify(byProvider)};\n` +
  `export const PRICES_BY_MODEL = ${JSON.stringify(byModel)};\n`;

const out = join(root, "lib", "prices.generated.js");
writeFileSync(out, header + body);
console.log(`wrote ${out} (${modelCount} models, ${Object.keys(byProvider).length} providers)`);
